### ISSUE TITLE
请问下这写库的版本依赖是多少

### ISSUE THREAD

**Issue by ElleryHao** [chuwt/chia-tx#1]
ImportError: cannot import name 'STRICT_MODE' from 'clvm_rs' (/home/wallet/elleryH/chia-tx/venv/lib/python3.8/site-packages/clvm_rs/__init__.py)
我一直爆出上述错误

**Comment by chuwt** [comment]
你好，太久没维护了，可能版本已经变了，这是之前的版本：
```
clvm: 0.9.6
clvm_rs: 0.1.7
clvm_tools: 0.4.3
```
